name: Eternity
version: 1.0
main: de.cric_hammel.eternity.Main
api-version: 1.20

commands:
   getstones:
      description: Gives you the powerful Infinity Stones
   getgauntlet:
      description: Gives you the mighty Infinity Gauntlet
   getkreearmor:
      description: Gives you the armor of the mighty Kree
   spawnkree:
      description: Spawns one og the mighty Kree
   dungeon:
      description: Teleports you into a dungeon of your choice
   getstoneuploader:
      description: Gives you the StoneUploader